using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TaskModel
{
    [RealtimeProperty(1, true, true)]
    private int _taskPage;
    [RealtimeProperty(2, true, true)]
    private Vector3 _markerPos;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TaskModel : RealtimeModel {
    public int taskPage {
        get {
            return _cache.LookForValueInCache(_taskPage, entry => entry.taskPageSet, entry => entry.taskPage);
        }
        set {
            if (this.taskPage == value) return;
            _cache.UpdateLocalCache(entry => { entry.taskPageSet = true; entry.taskPage = value; return entry; });
            InvalidateReliableLength();
            FireTaskPageDidChange(value);
        }
    }
    
    public UnityEngine.Vector3 markerPos {
        get {
            return _cache.LookForValueInCache(_markerPos, entry => entry.markerPosSet, entry => entry.markerPos);
        }
        set {
            if (this.markerPos == value) return;
            _cache.UpdateLocalCache(entry => { entry.markerPosSet = true; entry.markerPos = value; return entry; });
            InvalidateReliableLength();
            FireMarkerPosDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TaskModel model, T value);
    public event PropertyChangedHandler<int> taskPageDidChange;
    public event PropertyChangedHandler<UnityEngine.Vector3> markerPosDidChange;
    
    private struct LocalCacheEntry {
        public bool taskPageSet;
        public int taskPage;
        public bool markerPosSet;
        public UnityEngine.Vector3 markerPos;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        TaskPage = 1,
        MarkerPos = 2,
    }
    
    public TaskModel() : this(null) {
    }
    
    public TaskModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireTaskPageDidChange(int value) {
        try {
            taskPageDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireMarkerPosDidChange(UnityEngine.Vector3 value) {
        try {
            markerPosDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.TaskPage, (uint)_taskPage);
            length += WriteStream.WriteBytesLength((uint)PropertyID.MarkerPos, WriteStream.Vector3ToBytesLength());
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.taskPageSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.TaskPage, (uint)entry.taskPage);
            }
            if (entry.markerPosSet) {
                length += WriteStream.WriteBytesLength((uint)PropertyID.MarkerPos, WriteStream.Vector3ToBytesLength());
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.TaskPage, (uint)_taskPage);
            stream.WriteBytes((uint)PropertyID.MarkerPos, WriteStream.Vector3ToBytes(_markerPos));
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.taskPageSet || entry.markerPosSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.taskPageSet) {
                stream.WriteVarint32((uint)PropertyID.TaskPage, (uint)entry.taskPage);
                didWriteProperties = true;
            }
            if (entry.markerPosSet) {
                stream.WriteBytes((uint)PropertyID.MarkerPos, WriteStream.Vector3ToBytes(entry.markerPos));
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.TaskPage: {
                    int previousValue = _taskPage;
                    _taskPage = (int)stream.ReadVarint32();
                    bool taskPageExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.taskPageSet);
                    if (!taskPageExistsInChangeCache && _taskPage != previousValue) {
                        FireTaskPageDidChange(_taskPage);
                    }
                    break;
                }
                case (uint)PropertyID.MarkerPos: {
                    UnityEngine.Vector3 previousValue = _markerPos;
                    _markerPos = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    bool markerPosExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.markerPosSet);
                    if (!markerPosExistsInChangeCache && _markerPos != previousValue) {
                        FireMarkerPosDidChange(_markerPos);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _taskPage = taskPage;
        _markerPos = markerPos;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
