using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TaskModel
{
    [RealtimeProperty(1, true, true)]
    private int _taskPage;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TaskModel : RealtimeModel {
    public int taskPage {
        get {
            return _cache.LookForValueInCache(_taskPage, entry => entry.taskPageSet, entry => entry.taskPage);
        }
        set {
            if (this.taskPage == value) return;
            _cache.UpdateLocalCache(entry => { entry.taskPageSet = true; entry.taskPage = value; return entry; });
            InvalidateReliableLength();
            FireTaskPageDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TaskModel model, T value);
    public event PropertyChangedHandler<int> taskPageDidChange;
    
    private struct LocalCacheEntry {
        public bool taskPageSet;
        public int taskPage;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        TaskPage = 1,
    }
    
    public TaskModel() : this(null) {
    }
    
    public TaskModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireTaskPageDidChange(int value) {
        try {
            taskPageDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.TaskPage, (uint)_taskPage);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.taskPageSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.TaskPage, (uint)entry.taskPage);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.TaskPage, (uint)_taskPage);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.taskPageSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.taskPageSet) {
                stream.WriteVarint32((uint)PropertyID.TaskPage, (uint)entry.taskPage);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.TaskPage: {
                    int previousValue = _taskPage;
                    _taskPage = (int)stream.ReadVarint32();
                    bool taskPageExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.taskPageSet);
                    if (!taskPageExistsInChangeCache && _taskPage != previousValue) {
                        FireTaskPageDidChange(_taskPage);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _taskPage = taskPage;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
